# HOW TO READ A IMAGE IN OPENCV

In [1]:
import cv2

## Read the image from the path

* 0 for grayscale 
* 1 for color
* -1 for alpha channel


In [3]:
img =cv2.imread('First_image.jpg' , 0)
print(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
cv2.imshow('image' , img) # display the image
k = cv2.waitKey(0) # 0 means the window will be closed when any key is pressed
if k == 27: # 27 is the ASCII value of Esc key
    cv2.destroyAllWindows() # close all the windows
elif k == ord('s'): # ord() is used to get the ASCII value of the character
    cv2.imwrite('First_image_copy.jpg' , img) # save the image
    cv2.destroyAllWindows() # close all the windows

# How to Read, Write, Show Videos from Camera in OpenCV

In [2]:
cap = cv2.VideoCapture(0) # 0 means the default camera
fourcc = cv2.VideoWriter_fourcc(*'XVID') # fourcc is a 4-byte code used to specify the video codec
out = cv2.VideoWriter('output.avi' , fourcc , 20.0 , (640 , 480)) # 20.0 is the frame rate , (640 , 480) is the frame size

print(cap.isOpened()) # check if the camera is opened or not

while(cap.isOpened()):
    ret , frame = cap.read() # ret is a boolean variable which returns true if the frame is available
    if ret == True : 
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) # get the width of the frame
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) # get the height of the frame
        
        out.write(frame) # write the frame into the output file
        
        gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY) # convert the frame into gray scale
        
        cv2.imshow('frame' , gray) # display the frame
        
        if cv2.waitKey(1) == ord('q'):
            break
    else:
        break
    

cap.release() # release the camera
out.release() # release the output file
cv2.destroyAllWindows() # close all the windows

True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0

KeyboardInterrupt: 

: 

# Draw geometric shapes on images using Python OpenCV

In [26]:
import numpy as np
import cv2 

# read color image
#img = cv2.imread('First_image.jpg' , 1)


img = np.zeros([524,524,3] , np.uint8) #

# draw a line
# img = cv2.line(img , (0,0) , (524,524) , (0,255,0) , 1 )
# img = cv2.line(img , (524,0) , (0,524) , (0,255,0) , 1 )

# # Create a aroundline 
# img = cv2.arrowedLine(img , (0,0) , (524,524) , (0,255,0) , 1)

img = cv2.rectangle(img , (100,100) , (200,200) , (0,0,255) , 1) # 1 is the thickness of the rectangle
img = cv2.circle(img , (300,300) , 50 , (0,0,255) , -1) # -1 means fill the circle with the color

# Write sime in image

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img , 'Open CV' , (50,50) , font , 1 , (255,255,255) , 1 , cv2.LINE_AA)


poly = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
cv2.polylines(img , [poly] , True , (0,255,255) , 1) # False means the points are not connected




cv2.imshow('image 1' , img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

# Create Graphics with opencv2 


In [20]:
import numpy as np

import cv2 

# create a image with the (600,300)
img = np.zeros((600,900,3) , np.uint8)

cv2.rectangle(img , (0,0) , (900,400) , (255,255,85) , -1)
cv2.rectangle(img , (0,400) , (900,600) , (75,180,70) , -1)

# DRAW SUN
cv2.circle(img , (100,100) , 50 , (0,255,255) , -1)
# draw tree 
cv2.rectangle(img , (400,200) , (450,400) , (0,255,0) , -1)


triangle2 = np.array([[640,460],[780,460], [710,200]], dtype=np.int32) #array to darw fillpoly

cv2.fillPoly(img, [triangle2], (75,180,70)) # fillpoly to draw triangle

cv2.imshow('myimage' , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Setting Camera Parameters in OpenCV Python

In [2]:
import cv2
cap = cv2.VideoCapture(0)

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 3000)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 3000)


while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:

       gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
       cv2.imshow('frame', gray)

       if cv2.waitKey(1) & 0xFF == ord('q'):
         break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# Show Date and Time on Videos using OpenCV Python

In [2]:
import cv2 
import datetime 

cap = cv2.VideoCapture(0)
cap.set(3 , 3000)
while(cap.isOpened()):
    ret , frame = cap.read()
    
    if ret == True : 
        
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = 'Width : ' +str(cap.get(3)) +'Hieght:' +str(cap.get(4))
        
        datet = str(datetime.datetime.now())
        # Add text 
        
        frame = cv2.putText( frame , text , (10,50) , font , 1 , (0,255,255) , 1)
        frame = cv2.putText( frame , datet , (10,100) , font , 1 , (0,255,255) , 1)
        
        cv2.imshow('frame' , frame)
        
        if cv2.waitKey(1) & 0xFF == ord('q'): 
            break
    else :
        break

cap.release()
cv2.destroyAllWindows()
        
        

# Handle Mouse Events in OpenCV 

### Example 1

In [5]:
import cv2
import numpy as np

events = [i for i in dir(cv2) if 'EVENT' in i] # get all the events in cv2
print(events) # print all the events

def click_events(event , x , y , flags , param) : 
    
    if event == cv2.EVENT_LBUTTONDOWN :
        print(x , ',' , y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = str(x) + ',' + str(y)
        cv2.putText(img , text , (x,y) , font , 1 , (255,255,0) , 1)
        cv2.imshow('image' , img)
    if event == cv2.EVENT_RBUTTONDOWN :
        blue = img[y,x,0] # get the blue value of the pixel
        green = img[y,x,1] # get the green value of the pixel
        red = img[y,x,2] # get the red value of the pixel
        font = cv2.FONT_HERSHEY_SIMPLEX # font style
        text = str(blue) + ',' + str(green) + ',' + str(red) # text to be displayed
        cv2.putText(img , text , (x,y) , font , 1 , (0,255,255) , 1) # put the text on the image
        cv2.imshow('image' , img)# display the image
        

img = cv2.imread('First_image.jpg' , 1)
cv2.imshow('image' , img)

cv2.setMouseCallback('image' , click_events) # call the click_events function when the mouse is clicked

cv2.waitKey(0)
cv2.destroyAllWindows()
    

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']
469 , 365
575 , 333
506 , 307
403 , 303
394 , 355
399 , 382
337 , 418
398 , 438
413 , 460
413 , 484
330 , 470
317 , 293
299 , 344


### Example 2

In [ ]:
import cv2
import numpy as np

def click_events(event , x , y , flags , param) : 
    if event == cv2.EVENT_LBUTTONDOWN : # if the left button of the mouse is clicked
        
        
